### PR TITLE
Update jstree.Rd

### PR DESCRIPTION
**Pull request by ismirsehregal**
Provide a hint on how to use Font Awesome Icons.

### CODE REVIEW

**Comment by ismirsehregal** [comment]
Furthermore it might be of interest for others, that also local images (www folder) can be passed to the `icon` argument.

**Comment by stla** [comment]
Thanks! I did the change but in the roxygen code, not in the Rd file.
I didn't know for the images, I will do an example.

**Comment by ismirsehregal** [comment]
After posting this yesterday I saw that `shinyTree` has a related example (also including images):

https://github.com/shinyTree/shinyTree/tree/master/inst/examples/13-icons

**Comment by stla** [comment]
I did the example. That is very nice. Thanks again.

**Comment by stla** [comment]
Yes, we can close. You can use `suppressMessages()`.

**Pull request closed without merging**
